# Generated by Django 2.2.12 on 2021-01-16 15:16

from django.db import migrations, models
import django.db.models.deletion
import tooks.ImageStorage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_img', models.ImageField(storage=tooks.ImageStorage.ImageStorage(), upload_to='c_img')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20, verbose_name='种类')),
                ('age', models.IntegerField(verbose_name='宠物年龄')),
                ('sex', models.CharField(max_length=10, verbose_name='宠物性别')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(verbose_name='价格')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('c_img', models.CharField(max_length=100, verbose_name='图片')),
                ('way', models.CharField(max_length=50, verbose_name='方式')),
                ('describe', models.TextField(verbose_name='内容')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
