# Generated by Django 2.2.12 on 2021-01-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100, verbose_name='内容')),
                ('image_one', models.ImageField(default='', upload_to='one', verbose_name='第一张图片')),
                ('image_two', models.ImageField(default='', upload_to='two', verbose_name='第二张图片')),
                ('image_three', models.ImageField(default='', upload_to='three', verbose_name='第三张图片')),
                ('image_four', models.ImageField(default='', upload_to='four', verbose_name='第四张图片')),
                ('image_five', models.ImageField(default='', upload_to='five', verbose_name='第五张图片')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=1, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('parent_id', models.IntegerField(default=0, verbose_name='哪个评论的回复')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('mutual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Mutual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('mutual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Mutual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
