# Generated by Django 2.2.12 on 2021-01-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCloset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=30, verbose_name='衣服名称')),
                ('avatar', models.ImageField(upload_to='衣服图片')),
                ('season', models.CharField(max_length=20, verbose_name='适用季节')),
                ('style', models.CharField(max_length=30, verbose_name='款式')),
                ('function', models.CharField(max_length=30, verbose_name='功能')),
                ('remark', models.TextField(verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
